# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170809_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='slug',
            field=models.SlugField(default='ROOT', max_length=100),
            preserve_default=False,
        ),
    ]
