# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menunode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='belongs_to',
            field=models.CharField(default='main_menu', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menunode',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
